name: Install Certificate for Application

# NOTE: at this point DNS should be configured to the vm instance external ip including www path
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email for certbot'
        required: true
        type: string
      app-url:
        description: 'Domain WITHOUT www or http(s)://'
        required: true
        type: string

env:
  HOST_IP: ${{ secrets.HOST_IP }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  EMAIL: ${{ inputs.email }}
  APP_DOMAIN: ${{ inputs.app-url }}
  
jobs:
  setup-reverse-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: SSH into VM and setup nginx reverse proxy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.HOST_IP }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ env.SSH_KEY }}
        envs: EMAIL, APP_DOMAIN
        script: |
          sudo apt -y update
          sudo apt -y install snapd
          sudo snap install --classic certbot
          sudo ln -s /snap/bin/certbot /usr/bin/certbot
          sudo certbot --nginx --non-interactive --agree-tos -m $EMAIL -d $APP_DOMAIN -d www.$APP_DOMAIN
