name: Docker Compose Angular Java Deployment

on:
  push:
    branches: [ 'main' ]
    
env:
  ENVIRONMENT: production
  VERSION: 1.0.0
  BACKEND_NAME: lock-pass-api
  FRONTEND_NAME: lock-pass-ui
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DOCKER_REPO_PATH: ${{ secrets.DOCKER_USERNAME }}/
  
jobs:
  backend-upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Java setup
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - run: mvn -f ${{ env.BACKEND_NAME }}/pom.xml versions:set -DnewVersion=${{ env.VERSION }}
    - run: mvn -f ${{ env.BACKEND_NAME }}/pom.xml clean install
    - run: mkdir ${{ env.ENVIRONMENT }} && cp ${{ env.BACKEND_NAME }}/target/*.jar ${{ env.ENVIRONMENT }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BACKEND_NAME }}-${{ env.VERSION }}
        path: ${{ env.ENVIRONMENT }}
        
  frontend-upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - run: cd ${{ env.FRONTEND_NAME }} && npm version ${{ env.VERSION }}
    - run: cd ${{ env.FRONTEND_NAME }} && npm install
    - run: cd ${{ env.FRONTEND_NAME }} && npm run test
    - run: cd ${{ env.FRONTEND_NAME }} && npm run build-${{ env.ENVIRONMENT }}
    
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FRONTEND_NAME }}-${{ env.VERSION }}
        path: ${{ env.FRONTEND_NAME }}/dist
      
  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: [backend-upload-artifact, frontend-upload-artifact]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - run: mkdir ${{ env.BACKEND_NAME }}/target
    - run: mkdir ${{ env.FRONTEND_NAME }}/dist
    
    - name: Download backend jar artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.BACKEND_NAME }}-${{ env.VERSION }}
        path: ${{ env.BACKEND_NAME }}/target

    - name: Download frontend dist
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.FRONTEND_NAME }}-${{ env.VERSION }}
        path: ${{ env.FRONTEND_NAME }}/dist
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: docker compose build
    - run: docker compose push
        
  deploy:
    runs-on: ubuntu-latest
    needs: push-to-dockerhub
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Copy compose file to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./compose.yaml"
        target: lock-pass/
        
    - name: Pull and run docker images in VM   
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        envs: ENVIRONMENT, VERSION, DB_USERNAME, DB_PASSWORD, DOCKER_REPO_PATH
        script: |
          cd lock-pass
          sudo -E docker compose rm -v -s -f
          sudo docker images -aq | sudo xargs docker rmi -f || true
          sudo -E docker compose pull
          sudo -E docker compose up -d